---
version: "3.9"

x-var:
  - &POSTGRES_USER
    postgres
  - &POSTGRES_PASSWORD
    default
  - &POSTGRES_DATABASE
    postgres

x-flyway-vars: &flyway-vars
  FLYWAY_URL: jdbc:postgresql://database:5432/postgres
  FLYWAY_USER: *POSTGRES_USER
  FLYWAY_PASSWORD: *POSTGRES_PASSWORD
  FLYWAY_BASELINE_ON_MIGRATE: true

x-postgres-vars: &postgres-vars
  POSTGRES_HOST: database
  POSTGRES_USER: *POSTGRES_USER
  POSTGRES_PASSWORD: *POSTGRES_PASSWORD
  POSTGRES_DATABASE: *POSTGRES_DATABASE

x-python-vars: &python-vars
  PIP_NO_CACHE_DIR: off
  PIP_DISABLE_PIP_VERSION_CHECK: on
  PIP_DEFAULT_TIMEOUT: 100
  POETRY_VERSION: 1.2.2
  POETRY_HOME: /opt/poetry
  POETRY_VIRTUALENVS_IN_PROJECT: true
  POETRY_NO_INTERACTION: 1
  PYSETUP_PATH: /application
  VENV_PATH: /application/.venv
  PYTHONDONTWRITEBYTECODE: 1
  PYTHONUNBUFFERED: 1
  PYTHONPATH: /application/app/src

services:
  database:
    image: postgres:15
    container_name: database
    environment:
      <<: *postgres-vars
    healthcheck:
      test: ["CMD", "pg_isready", "-U", *POSTGRES_USER]
    ports: ["5432:5432"]

  migrations:
    image: flyway/flyway:9-alpine
    container_name: migrations
    command: info migrate info
    volumes: ["./backend/db/migrations:/flyway/sql:ro"]
    environment:
      <<: *flyway-vars
      FLYWAY_DEFAULT_SCHEMA: USERS
    depends_on:
      database:
        condition: service_healthy

  migrations-go:
    profiles: ["go", "all"]
    image: flyway/flyway:9-alpine
    container_name: migrations-go
    command: info migrate info
    volumes: ["./backend-go/db/migrations:/flyway/sql:ro"]
    environment:
      <<: *flyway-vars
      FLYWAY_DEFAULT_SCHEMA: go_api
    depends_on:
      database:
        condition: service_healthy

  migrations-py:
    profiles: ["python", "all"]
    image: flyway/flyway:9-alpine
    container_name: migrations-py
    command: info migrate info
    volumes: ["./backend-py/db/migrations:/flyway/sql:ro"]
    environment:
      <<: *flyway-vars
      FLYWAY_DEFAULT_SCHEMA: py_api
    depends_on:
      database:
        condition: service_healthy

  backend:
    container_name: backend
    entrypoint: sh -c "npm i && npm run start:dev"
    environment:
      <<: *postgres-vars
      NODE_ENV: development
    image: node:20-bullseye
    ports: ["3001:3000"]
    volumes: ["./backend:/app", "/app/node_modules"]
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:3000/api"]
    working_dir: "/app"
    depends_on:
      migrations:
        condition: service_started

  backend-go:
    profiles: ["go", "all"]
    image: cosmtrek/air:latest
    working_dir: /app # has to be the same as mapped vol
    volumes: ["./backend-go/:/app", "/app/docs", "/app/tmp"]
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:3000/health"]
    container_name: backend-go
    environment:
      <<: *postgres-vars
    entrypoint: sh -c "go install github.com/swaggo/swag/cmd/swag@latest && swag init && swag fmt && /go/bin/air"
    ports: ["3005:3000"]
    depends_on:
      migrations-go:
        condition: service_started

  backend-py-model-generator:
    profiles: ["python", "all"]
    image: python:3.11-slim-buster # DO NOT change, as it breaks the module.
    container_name: backend-py-model-generator
    environment:
      <<: *postgres-vars
    entrypoint: /app/generate-models.sh
    volumes: 
      - "./backend-py/src/v1/models:/app/models"
      - "./backend-py/generate-models.sh:/app/generate-models.sh"
    depends_on:
      migrations-py:
        condition: service_completed_successfully

  backend-py:
    profiles: ["python", "all"]
    image: python:3.11
    container_name: backend-py
    entrypoint: /application/start-local.sh
    volumes: ["./backend-py:/application", "/application/.venv"]
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:3000"]
    environment:
      <<: [*postgres-vars, *python-vars]
    ports: ["3003:3000"]
    depends_on:
      backend-py-model-generator:
        condition: service_started

  backend-py-test:
    profiles: ["python", "all"]
    image: python:3.11
    container_name: backend-py-test
    entrypoint: /application/run-unit-tests.sh
    volumes: ["./backend-py:/application", "/application/.venv"]
    environment:
      <<: [*postgres-vars, *python-vars]
    depends_on:
      backend-py:
        condition: service_healthy

  frontend:
    container_name: frontend
    entrypoint: sh -c "npm ci && npm run dev"
    environment:
      NODE_ENV: development
      PORT: 3000
      BACKEND_URL: http://backend:3000
    image: node:20-bullseye
    ports: ["3000:3000"]
    volumes: ["./frontend:/app", "/app/node_modules"]
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:3000"]
    working_dir: "/app"
    depends_on:
      backend:
        condition: service_healthy
