{{- if and .Values.backendPy.pdb  .Values.backendPy.pdb.enabled }}
---
apiVersion: policy/v1
kind: PodDisruptionBudget
metadata:
  name: {{ include "backendPy.fullname" . }}
  labels:
    {{- include "backendPy.labels" . | nindent 4 }}
spec:
  selector:
    matchLabels:
      app.kubernetes.io/name: {{ include "backendPy.name" . }}
      app.kubernetes.io/instance: {{ .Release.Name }}
  minAvailable: {{ .Values.backendPy.pdb.minAvailable }}
{{- end }}
