{{- if .Values.backendPy.enabled }}
---
apiVersion: v1
kind: Service
metadata:
  name: {{ include "backendPy.fullname" . }}
  labels:
    {{- include "backendPy.labels" . | nindent 4 }}
spec:
  type: {{ .Values.backendPy.service.type }}
  ports:
    - port: {{ .Values.backendPy.service.port }}
      targetPort: http
      protocol: TCP
      name: http
  selector:
    {{- include "backendPy.selectorLabels" . | nindent 4 }}
{{- end }}
