# Default values for charts.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

component: database
image:
  tag: latest
  registry: ghcr.io
org: ~
repo: ~
resources:
  pvc:
    mount: /var/lib/postgresql
    size: 256Mi
zone: ~

backups:
  component: database-backup
  dir: /backups/
  image: bcgovimages/backup-container:latest
  job:
    retries: 0
    history: 5
    keep:
      successful: 5
      failed: 2
  pvc-size: 256Mi
  schedule: "05 8 * * *" # Run daily at 8:05 AM UTC
  strategy: rolling

# Templated/calculated values
# - Consume with: {{ tpl "whatever" . }}
id:
  database: "{{ .Values.repo }}-{{ .Values.zone }}-{{ .Values.component }}"
  backups: "{{ .Values.repo }}-{{ .Values.zone }}-{{ .Values.backups.component }}"
