{{/* 
Secret for database
- Uses annotation to prevent removal from zone=(test|prod)
- Reuses existing passwords, if found
*/}}
---
apiVersion: v1
kind: Secret
{{- include "metadata" . }}
{{- if or (eq (.Values.zone | toString ) "test") (eq (.Values.zone | toString ) "prod") }}
  annotations:
    "helm.sh/resource-policy": "keep" # Retain secret for non-PRs (test|prod)
{{- end }}
data:
  database-name: {{ .Values.database.name | b64enc }}
  database-user: {{ .Values.database.user | b64enc }}
  {{- $secretData := (lookup "v1" "Secret" .Release.Namespace (tpl .Values.id .)).data | default dict }}
  database-password: {{ get $secretData "database-password" | default (randAlphaNum 32 | b64enc ) | quote }}
