# Default values for charts.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

repo: ~
zone: ~

database:
  component: database
  name: default
  user: default

# Templated/calculated values
# - Consume with: {{ tpl "whatever" . }}
id: "{{ .Values.repo }}-{{ .Values.zone }}-{{ .Values.database.component }}"
