{{- if .Values.backendGo.enabled }}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "backendGo.fullname" . }}
  labels:
    {{- include "backendGo.labels" . | nindent 4 }}
spec:
  strategy:
    type: {{ .Values.backendGo.deploymentStrategy }}
  {{- if not .Values.backendGo.autoscaling.enabled }}
  replicas: {{ .Values.backendGo.replicaCount }}
  {{- end }}
  selector:
    matchLabels:
      {{- include "backendGo.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      labels:
        {{- include "backendGo.labels" . | nindent 8 }}
    spec:
      {{- if .Values.backendGo.podSecurityContext }}
      securityContext:
        {{- toYaml .Values.backendGo.podSecurityContext | nindent 12 }}
      {{- end }}
      initContainers:
        - name: {{ include "backendGo.fullname" . }}-init
          image: "{{.Values.global.registry}}/{{.Values.global.repository}}/migrations-go:{{ .Values.global.tag | default .Chart.AppVersion }}"
          imagePullPolicy: {{ default "IfNotPresent" .Values.backendGo.imagePullPolicy }}
          envFrom:
            - secretRef:
                name: {{.Release.Name}}-go-flyway
          env:
            - name: FLYWAY_BASELINE_ON_MIGRATE
              value: "true"
            - name: FLYWAY_DEFAULT_SCHEMA
              value: "go_api"
            - name: FLYWAY_CONNECT_RETRIES
              value: "10"
            - name: FLYWAY_GROUP
              value: "true"
          resources:
            requests:
              cpu: 20m
              memory: 150Mi
      containers:
        - name: {{ include "backendGo.fullname" . }}
          {{- if .Values.backendGo.securityContext }}
          securityContext:
            {{- toYaml .Values.backendGo.securityContext | nindent 12 }}
          {{- end }}
          image: "{{.Values.global.registry}}/{{.Values.global.repository}}/backend-go:{{ .Values.global.tag | default .Chart.AppVersion }}"
          imagePullPolicy: {{ default "IfNotPresent" .Values.backendGo.imagePullPolicy }}
          envFrom:
            - secretRef:
                name: {{.Release.Name}}-go
          env:
            - name: LOG_LEVEL
              value: info
          ports:
            - name: http
              containerPort: {{ .Values.backendGo.service.targetPort }}
              protocol: TCP
          readinessProbe:
            httpGet:
              path: /
              port: http
              scheme: HTTP
            initialDelaySeconds: 5
            periodSeconds: 2
            timeoutSeconds: 2
            successThreshold: 1
            failureThreshold: 30
          livenessProbe:
            successThreshold: 1
            failureThreshold: 3
            httpGet:
              path: /
              port: 3000
              scheme: HTTP
            initialDelaySeconds: 15
            periodSeconds: 30
            timeoutSeconds: 5
          resources: # this is optional
            requests:
              cpu: 20m
              memory: 150Mi
      {{- with .Values.backendGo.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.backendGo.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      affinity:
        podAntiAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            - labelSelector:
                matchExpressions:
                  - key: app.kubernetes.io/name
                    operator: In
                    values:
                      - {{ include "backendGo.fullname" . }}
                  - key: app.kubernetes.io/instance
                    operator: In
                    values:
                      - {{ .Release.Name }}
              topologyKey: "kubernetes.io/hostname"

{{- end }}
