{{- if and .Values.backendGo.pdb  .Values.backendGo.pdb.enabled }}
---
apiVersion: policy/v1
kind: PodDisruptionBudget
metadata:
  name: {{ include "backendGo.fullname" . }}
  labels:
    {{- include "backendGo.labels" . | nindent 4 }}
spec:
  selector:
    matchLabels:
      app.kubernetes.io/name: {{ include "backendGo.fullname" . }}
  minAvailable: {{ .Values.backendGo.pdb.minAvailable }}
{{- end }}
