{{- if and .Values.global.secrets .Values.global.secrets.enabled}}
{{- $databaseUser := printf ""}}
{{- $databasePassword := printf ""}}
{{- $databaseName := printf ""}}
{{- $hostWithoutPort := printf ""}}
{{- $secretName := printf "%s-pguser-%s" .Values.global.databaseAlias .Values.global.config.databaseUser }}
{{- $databaseUser = .Values.global.config.databaseUser}}
{{- $secretObj := (lookup "v1" "Secret" .Release.Namespace $secretName ) }}
{{- if not $secretObj }}
  {{- fail (printf "Secret %s not found in namespace %s" $secretName .Release.Namespace) }}
{{- end }}
{{- $secretData := (get $secretObj "data") }}
{{- if not $secretData }}
  {{- fail (printf "Secret %s data not found in namespace %s" $secretName .Release.Namespace) }}
{{- end }}
{{- $databasePassword = get $secretData "password"  }}
{{- $databaseName = b64dec (get $secretData "dbname") }}
{{- $hostWithoutPort = printf "%s" (b64dec (get $secretData "pgbouncer-host"))  }}
---
apiVersion: v1
kind: Secret
metadata:
  name: {{ .Release.Name }}-java
  labels: {{- include "selectorLabels" . | nindent 4 }}
data:
  POSTGRES_PASSWORD: {{ $databasePassword | quote }}
  POSTGRES_USER: {{ $databaseUser | b64enc | quote }}
  POSTGRES_DATABASE: {{ $databaseName | b64enc | quote }}
  POSTGRES_HOST: {{ $hostWithoutPort | b64enc | quote }}
{{- end }}
