{{- if and .Values.backendJava.pdb  .Values.backendJava.pdb.enabled }}
---
apiVersion: policy/v1
kind: PodDisruptionBudget
metadata:
  name: {{ include "backendJava.fullname" . }}
  labels:
    {{- include "backendJava.labels" . | nindent 4 }}
spec:
  selector:
    matchLabels:
      app.kubernetes.io/name: {{ include "backendJava.name" . }}
      app.kubernetes.io/instance: {{ .Release.Name }}
  minAvailable: {{ .Values.backendJava.pdb.minAvailable }}
{{- end }}
