{{- if .Values.backendJava.enabled }}
---
apiVersion: v1
kind: Service
metadata:
  name: {{ include "backendJava.fullname" . }}
  labels:
    {{- include "backendJava.labels" . | nindent 4 }}
spec:
  type: {{ .Values.backendJava.service.type }}
  ports:
    - port: {{ .Values.backendJava.service.port }}
      targetPort: http
      protocol: TCP
      name: http
  selector:
    {{- include "backendJava.selectorLabels" . | nindent 4 }}
{{- end }}
