apiVersion: template.openshift.io/v1
kind: Template
parameters:
  - name: NAME
    description: Module name
    value: quickstart-openshift-backends
  - name: COMPONENT
    description: Component name
    value: backend-py
  - name: ZONE
    description: Deployment zone, e.g. pr-### or prod
    required: true
  - name: IMAGE_TAG
    description: Image tag to use
    value: latest
  - name: DOMAIN
    value: apps.silver.devops.gov.bc.ca
  - name: CPU_REQUEST
    value: "25m"
  - name: MEMORY_REQUEST
    value: "50Mi"
  - name: CPU_LIMIT
    value: "75m"
  - name: MEMORY_LIMIT
    value: "150Mi"
  - name: CPU_REQUEST_INIT
    value: "125m"
  - name: MEMORY_REQUEST_INIT
    value: "100Mi"
  - name: CPU_LIMIT_INIT
    value: "250m"
  - name: MEMORY_LIMIT_INIT
    value: "250Mi"
  - name: MIN_REPLICAS
    description: The minimum amount of replicas for the horizontal pod autoscaler.
    value: "3"
  - name: MAX_REPLICAS
    description: The maximum amount of replicas for the horizontal pod autoscaler.
    value: "5"
  - name: REGISTRY
    description: Container registry to import from (internal is image-registry.openshift-image-registry.svc:5000)
    value: ghcr.io
  - name: ORG_NAME
    description: Organization name, e.g. bcgov
    value: bcgov
  - name: PROMOTE
    description: Image (namespace/name:tag) to promote/import
    value: bcgov/quickstart-openshift-backends/backend-py:test
  - name: PROMOTE_MIGRATION
    description: Image (namespace/name:tag) for migration to promote/import
    value: bcgov/quickstart-openshift-backends/migrations-py:test
  - name: COMPONENT_DB_MIGRATION
    description: Component name for database migrations
    value: migrations-py
objects:
  - apiVersion: v1
    kind: ConfigMap
    metadata:
      name: "${COMPONENT}-configmap"
      namespace: logger-conf
      labels:
        app: "${NAME}-${ZONE}"
    data:
      logger.conf: |
        [loggers]
        keys=root,sqlalchemy,psycopg2

        [handlers]
        keys=console

        [formatters]
        keys=default

        [logger_root]
        level=INFO
        handlers=console
        qualname=root
        propagate=0

        [logger_sqlalchemy]
        level=DEBUG
        handlers=console
        qualname=sqlalchemy
        propagate=0

        [logger_psycopg2]
        level=DEBUG
        handlers=console
        qualname=psycopg2
        propagate=0

        [handler_console]
        class=StreamHandler
        formatter=default
        args=(sys.stdout,)

        [formatter_default]
        format=%(asctime)s.%(msecs)03d | %(levelname)s | %(name)s | %(funcName)s:%(lineno)d | %(message)s
        datefmt=%Y-%m-%d %H:%M:%S

  - apiVersion: v1
    kind: ImageStream
    metadata:
      labels:
        app: "${NAME}-${ZONE}"
      name: "${NAME}-${ZONE}-${COMPONENT}"
    spec:
      lookupPolicy:
        local: false
      tags:
        - name: "${IMAGE_TAG}"
          from:
            kind: DockerImage
            name: "${REGISTRY}/${PROMOTE}"
          referencePolicy:
            type: Local
  - apiVersion: v1
    kind: ImageStream
    metadata:
      labels:
        app: "${NAME}-${ZONE}"
      name: "${NAME}-${ZONE}-${COMPONENT_DB_MIGRATION}"
    spec:
      lookupPolicy:
        local: false
      tags:
        - name: "${IMAGE_TAG}"
          from:
            kind: DockerImage
            name: "${REGISTRY}/${PROMOTE_MIGRATION}"
          referencePolicy:
            type: Local
  - apiVersion: v1
    kind: DeploymentConfig
    metadata:
      labels:
        app: "${NAME}-${ZONE}"
      name: "${NAME}-${ZONE}-${COMPONENT}"
    spec:
      replicas: 1
      triggers:
        - type: ConfigChange
        - type: ImageChange
          imageChangeParams:
            automatic: true
            containerNames:
              - "${NAME}"
            from:
              kind: ImageStreamTag
              name: "${NAME}-${ZONE}-${COMPONENT}:${IMAGE_TAG}"
        - type: ImageChange
          imageChangeParams:
            automatic: true
            containerNames:
              - "${NAME}-${COMPONENT_DB_MIGRATION}"
            from:
              kind: ImageStreamTag
              name: "${NAME}-${ZONE}-${COMPONENT_DB_MIGRATION}:${IMAGE_TAG}"
      selector:
        deploymentconfig: "${NAME}-${ZONE}-${COMPONENT}"
      strategy:
        type: Rolling
      template:
        metadata:
          labels:
            app: "${NAME}-${ZONE}"
            deploymentconfig: "${NAME}-${ZONE}-${COMPONENT}"
        spec:
          containers:
            - image: "${NAME}-${ZONE}-${COMPONENT}:${IMAGE_TAG}"
              imagePullPolicy: Always
              name: "${NAME}"
              env:
                - name: POSTGRES_HOST
                  value: "${NAME}-${ZONE}-database:5432"
                - name: POSTGRES_DB
                  valueFrom:
                    secretKeyRef:
                      name: "${NAME}-${ZONE}-database"
                      key: database-name
                - name: POSTGRES_PASSWORD
                  valueFrom:
                    secretKeyRef:
                      name: "${NAME}-${ZONE}-database"
                      key: database-password
                - name: POSTGRES_USER
                  valueFrom:
                    secretKeyRef:
                      name: "${NAME}-${ZONE}-database"
                      key: database-user
                - name: PYTHONPATH
                  value: /application/app/src
              volumeMounts:
                - mountPath: /opt
                  name: logger-conf
              ports:
                - containerPort: 3000
                  protocol: TCP
              resources:
                requests:
                  cpu: "${CPU_REQUEST}"
                  memory: "${MEMORY_REQUEST}"
                limits:
                  cpu: "${CPU_LIMIT}"
                  memory: "${MEMORY_LIMIT}"
              readinessProbe:
                httpGet:
                  path: /
                  port: 3000
                  scheme: HTTP
                initialDelaySeconds: 5
                periodSeconds: 2
                timeoutSeconds: 2
                successThreshold: 1
                failureThreshold: 30
              livenessProbe:
                successThreshold: 1
                failureThreshold: 3
                httpGet:
                  path: /
                  port: 3000
                  scheme: HTTP
                initialDelaySeconds: 60
                periodSeconds: 30
                timeoutSeconds: 5
          volumes:
            - name: logger-conf
              configMap:
                name: "${COMPONENT}-configmap"
          initContainers:
            - name: "${NAME}-${COMPONENT_DB_MIGRATION}"
              image: "${NAME}-${ZONE}-${COMPONENT_DB_MIGRATION}:${IMAGE_TAG}"
              env:
                - name: FLYWAY_URL
                  value: "jdbc:postgresql://${NAME}-${ZONE}-database:5432/${NAME}"
                - name: FLYWAY_USER
                  valueFrom:
                    secretKeyRef:
                      name: "${NAME}-${ZONE}-database"
                      key: database-user
                - name: FLYWAY_PASSWORD
                  valueFrom:
                    secretKeyRef:
                      name: "${NAME}-${ZONE}-database"
                      key: database-password
                - name: FLYWAY_BASELINE_ON_MIGRATE
                  value: "true"
                - name: FLYWAY_DEFAULT_SCHEMA
                  value: "py-api"
              resources:
                requests:
                  cpu: "${CPU_REQUEST_INIT}"
                  memory: "${MEMORY_REQUEST_INIT}"
                limits:
                  cpu: "${CPU_LIMIT_INIT}"
                  memory: "${MEMORY_LIMIT_INIT}"
  - apiVersion: v1
    kind: Service
    metadata:
      labels:
        app: "${NAME}-${ZONE}"
      name: "${NAME}-${ZONE}-${COMPONENT}"
    spec:
      ports:
        - name: 3000-tcp
          protocol: TCP
          port: 80
          targetPort: 3000
      selector:
        deploymentconfig: "${NAME}-${ZONE}-${COMPONENT}"
  - apiVersion: route.openshift.io/v1
    kind: Route
    metadata:
      labels:
        app: "${NAME}-${ZONE}"
      name: "${NAME}-${ZONE}-${COMPONENT}"
    spec:
      host: "${NAME}-${ZONE}-${COMPONENT}.${DOMAIN}"
      port:
        targetPort: 3000-tcp
      to:
        kind: Service
        name: "${NAME}-${ZONE}-${COMPONENT}"
        weight: 100
      tls:
        termination: edge
        insecureEdgeTerminationPolicy: Redirect
  - apiVersion: autoscaling/v2
    kind: HorizontalPodAutoscaler
    metadata:
      labels:
        app: "${NAME}-${ZONE}"
      name: "${NAME}-${ZONE}-${COMPONENT}"
    spec:
      scaleTargetRef:
        apiVersion: apps.openshift.io/v1
        kind: DeploymentConfig
        name: "${NAME}-${ZONE}-${COMPONENT}"
      minReplicas: "${{MIN_REPLICAS}}"
      maxReplicas: "${{MAX_REPLICAS}}"
      metrics:
        - type: Resource
          resource:
            name: cpu
            target:
              type: Utilization
              averageUtilization: 100
