name: PR Validate

on:
  pull_request:
    types: [edited, opened, synchronize, reopened, ready_for_review]

concurrency:
  group: ${{ github.workflow }}-edit-${{ github.event.number }}
  cancel-in-progress: true
permissions: {}
jobs:
  validate:
    name: Validate PR
    permissions:
      contents: read          # Required for repository access
      pull-requests: write    # Required for commenting on PRs
    uses: bcgov/quickstart-openshift-helpers/.github/workflows/.pr-validate.yml@ca6579bdadf383a2513397081f963889b92823a4 # v1.1.0
    with:
      markdown_links: |
        - [Java](https://${{ github.event.repository.name }}-${{ github.event.number }}-backend-java.apps.silver.devops.gov.bc.ca)
        - [Py](https://${{ github.event.repository.name }}-${{ github.event.number }}-backend-py.apps.silver.devops.gov.bc.ca)

  results:
    name: Validate Results
    if: always()
    needs: [validate]
    runs-on: ubuntu-24.04
    steps:
      - if: contains(needs.*.result, 'failure') || contains(needs.*.result, 'cancelled')
        run: echo "Validation failed or was cancelled." && exit 1
      - run: echo "Success!"
